[tool.black]
line-length = 79

[tool.isort]
py_version = 310
extra_standard_library = ["typing_extensions"]
add_imports = ["from __future__ import annotations"]
line_length = 79
profile = "black"
combine_as_imports = true
combine_star = true

[tool.pyright]
pythonVersion = "3.10"
typeCheckingMode = "strict"
reportMissingModuleSource = "error"
reportCallInDefaultInitializer = "error"
reportImplicitStringConcatenation = "error"
reportMissingSuperCall = "error"
reportPropertyTypeMismatch = "error"
reportUninitializedInstanceVariable = "error"
reportUnnecessaryTypeIgnoreComment = "error"
reportUnusedCallResult = "error"