name: Poetry
on: [ pull_request, push ]
jobs:
  build:
    if: github.event.pull_request.user.type != 'Bot'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ '3.10' ]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Poetry
        run: pip install -U pip poetry
      - name: Install Dependencies & Build Lock File
        run: |
          rm poetry.lock
          poetry install
      - name: Push To GitHub
        continue-on-error: true
        run: |
          git pull
          git add ./
          git commit --reuse-message=HEAD
          git push
